### ISSUE TITLE
Update graphviz for server serving gviz?

### ISSUE THREAD

**Issue by Potherca** [oodavid/gviz#1]
The server responsible for the actual rendering seems to be running an older version of graphviz... Is an update expected anytime in the near future?

**Comment by oodavid** [comment]
There could be, TBH I just installed it from unbutu's repos - are there
significant developments in the newer versions?

_Kind Regards,_
_David King_
*
*
_Tel: +44(0)7939273963_
*Skype: oopstudios
Site: oodavid.com
Twitter: @oodavid http://twitter.com/oodavid
*

**Comment by Potherca** [comment]
There have been several improvements and additions. The only one I know off the top of my head is the addition of othogonal splines, but there are more. I could look them up if you want a specific list.
